---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alfredta/public_html/villa/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R out/* $DEPLOYPATH
    - /bin/cp -a out/.htaccess $DEPLOYPATH
    - /bin/echo "Deployed frontend to $DEPLOYPATH successfully"
